### PR TITLE
Adjusting coordinates for maps

### PR DESCRIPTION
**Pull request by Geph**
Adjusting coordinates for new maps

### CODE REVIEW

**Comment by Geph** [comment]
Okay I think I jammed them all together into the same branch / pull request ?

**Comment by jhenhapl** [comment]
> Okay I think I jammed them all together into the same branch / pull request ?

Did you upload the new habitable strip map? I don't see it here.

**Review by jackah2 — APPROVED** [review]
Awesome, looks good

**Comment by Geph** [comment]
@jackah2 I think I was able to put the two files into a single upload

**Pull request merged**
